spring:
  datasource:
    url: jdbc:postgresql://${host}:${port}/${db_name}
    username: ${db_user}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
secret: ${secret}